### ISSUE TITLE
Remove invenio-access dependency

### ISSUE THREAD

**Issue by ntarocco** [inveniosoftware/invenio-iiif#14]
Remove invenio-access dependency when invenio-files-rest is released.

**Comment by topless** [comment]
@ntarocco this is related to https://github.com/inveniosoftware/invenio-files-rest/issues/134, which requests the removal of `invenio-access` from `invenio-files-rest` dependencies. After a short talk with Lars it is not going to happen. 

I haven't removed the FIXME comment from the setup yet, to make sure we refer to the same thing.
