### ISSUE TITLE
roadmap?

### ISSUE THREAD

**Issue by mnyrop** [inveniosoftware/invenio-iiif#25]
hello maintainers!

2 quick questions:
+ is there a roadmap for this module?
+ is there a plan / any appetite for adding support for the [IIIF presentation API](https://iiif.io/technical-details/)?

Thanks for your time and the work that you do.

**Comment by lnielsen** [comment]
We only have a roadmap for the overall project: https://inveniosoftware.org/roadmap/ 

Regarding IIIF Presentation API, there are no immediate plans, but it might be part of the InvenioRDM project where some of the partners have advanced use cases
https://inveniosoftware.org/products/rdm/

**Comment by mnyrop** [comment]
Thanks!

**Comment by lnielsen** [comment]
Sorry for the very late reply. Missed the ticket.
